### ISSUE TITLE
Calculate total voucher operations statistics

### ISSUE THREAD

**Issue by starkmsu** [OpenMAVN/MAVN.Service.DashboardStatistics#11]
1) Introduce a new table for calculating voucher operations statistics per Partner
{
Guid id - db key,
Guid PartnerId,
Enum OperationType - Buy, Redeem,
decimal Sum - total sum of operations fo this type and in particular currency,
string Currency,
int TotalCount - total number of operations of such type in such Currency for this partner
}
This table must have a complex non-qunique index on PartnerId and OperationType
2) Subscribe to SmartVoucherUsedEvent (if such subscription is not yet implemented)
3) During the processing of SmartVoucherSoldEvent and SmartVoucherUsedEvent (subscribe to SmartVoucherSoldEvent) get a redis lock on %PartnerId%_%OperationType% combination and update the corresponding total sum for specific Currency (example - https://github.com/OpenMAVN/MAVN.Service.SmartVouchers/blob/master/src/MAVN.Service.SmartVouchers.DomainServices/VouchersService.cs#L104)
4) Add new API - ISmartVouchersApi - and expose endpoint in it that return a collection of total voucher statistics for a list of known currencies:
[Post("/api/smartvouchers/totals")]
Task<VoucherStatisticsResponse> GetTotalStatisticsAsync(Guid[] partnerIds);
VoucherStatisticsResponse:
{
 CurrenciesStatistics: [
  {
    "Currency": "...", // currency
    "TotalPurchasesCost": "..", //Sum value from the table for Buy operation type
    "TotalPurchasesCount": "...", //TotalCount value from the table for Buy operation type
    "TotalRedeemedVouchersCost": "...", //Sum value from the table for Redeem operation type
    "TotalRedeemedVouchersCount": "...", //TotalCount value from the table for Redeem operation type
  }
 ]
}

**Comment by HannaAndreevna** [comment]
Implemented
